<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="DESKTOP-FO6JLLM"><DocLocation><![CDATA[E:\DataDrivenFramework\Driver\Driver4]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Driver4]]></DName>
<Res><![CDATA[Res32]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[tr1]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "tr1" started.]]></Details>
<Time><![CDATA[30-03-2022 - 15:57:15]]></Time>
<TimeTick>1648636035</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="Action1" SourceLine="8" >
<Disp><![CDATA[tr1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 15:57:51]]></Time>
<TimeTick>1648636071</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"WpfTabStrip"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 15:57:51]]></Time>
<TimeTick>1648636071</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 15:57:51]]></Time>
<TimeTick>1648636071</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" status="Warning" nType="Parent description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="54" status="Failed" nType="Run Error" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="53" status="Failed" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 15:57:51]]></Time>
<TimeTick>1648636071</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;WpfTabStrip&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (31): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 15:57:51]]></Time>
<TimeTick>1648636071</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="30" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[byNumberRadio]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"byNumberRadio"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 15:58:51]]></Time>
<TimeTick>1648636131</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 15:58:51]]></Time>
<TimeTick>1648636131</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="62" status="Failed" nType="Run Error" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberRadio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 15:58:51]]></Time>
<TimeTick>1648636131</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;byNumberRadio&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (32): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfRadioButton(&quot;byNumberRadio&quot;).Set&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 15:58:51]]></Time>
<TimeTick>1648636131</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="65" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="31" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"byNumberWatermark"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:13]]></Time>
<TimeTick>1648636153</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:13]]></Time>
<TimeTick>1648636153</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="75" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="74" status="Failed" nType="Run Error" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberWatermark]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="64" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:13]]></Time>
<TimeTick>1648636153</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;byNumberWatermark&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (33): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfEdit(&quot;byNumberWatermark&quot;).Set &quot;7&quot;&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:13]]></Time>
<TimeTick>1648636153</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="77" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="32" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SEARCH]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"SEARCH"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:34]]></Time>
<TimeTick>1648636174</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:34]]></Time>
<TimeTick>1648636174</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="87" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="86" status="Failed" nType="Run Error" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[SEARCH]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="76" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:34]]></Time>
<TimeTick>1648636174</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;SEARCH&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (34): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfButton(&quot;SEARCH&quot;).Click&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:34]]></Time>
<TimeTick>1648636174</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="89" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="33" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"NEW&nbsp;SEARCH"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:55]]></Time>
<TimeTick>1648636195</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:55]]></Time>
<TimeTick>1648636195</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="99" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="98" status="Failed" nType="Run Error" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[NEW SEARCH]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="88" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:55]]></Time>
<TimeTick>1648636195</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;NEW SEARCH&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (35): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfButton(&quot;NEW SEARCH&quot;).Click&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:55]]></Time>
<TimeTick>1648636195</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="101" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="34" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"WpfTabStrip"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:56]]></Time>
<TimeTick>1648636196</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 15:59:56]]></Time>
<TimeTick>1648636196</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="103" status="Warning" nType="Parent description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="102" status="Failed" nType="Run Error" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[WpfTabStrip]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"WpfTabStrip"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:17]]></Time>
<TimeTick>1648636217</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:17]]></Time>
<TimeTick>1648636217</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="113" status="Warning" nType="Parent description" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="112" status="Failed" nType="Run Error" >
<Disp><![CDATA[WpfTabStrip]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="100" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:17]]></Time>
<TimeTick>1648636217</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;WpfTabStrip&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (31): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfTabStrip(&quot;WpfTabStrip&quot;).Select &quot;SEARCH ORDER&quot;&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:17]]></Time>
<TimeTick>1648636217</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="30" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[byNumberRadio]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"byNumberRadio"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:38]]></Time>
<TimeTick>1648636238</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:38]]></Time>
<TimeTick>1648636238</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="121" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="120" status="Failed" nType="Run Error" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberRadio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="114" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:38]]></Time>
<TimeTick>1648636238</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;byNumberRadio&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (32): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfRadioButton(&quot;byNumberRadio&quot;).Set&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:38]]></Time>
<TimeTick>1648636238</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="123" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="31" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"byNumberWatermark"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:38]]></Time>
<TimeTick>1648636238</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:38]]></Time>
<TimeTick>1648636238</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="125" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="124" status="Failed" nType="Run Error" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberWatermark]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[byNumberWatermark]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"byNumberWatermark"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:59]]></Time>
<TimeTick>1648636259</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:59]]></Time>
<TimeTick>1648636259</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="135" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="134" status="Failed" nType="Run Error" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[byNumberWatermark]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="122" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:59]]></Time>
<TimeTick>1648636259</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;byNumberWatermark&quot; object's parent &quot;HPE MyFlight Sample Applicatio&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: E:\DataDrivenFramework\Driver\Driver4\Library1.qfl<BR/>Line (33): &quot;WpfWindow(&quot;HPE MyFlight Sample Applicatio&quot;).WpfEdit(&quot;byNumberWatermark&quot;).Set &quot;7&quot;&quot;.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:59]]></Time>
<TimeTick>1648636259</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="137" status="Failed" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="32" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[SEARCH]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"SEARCH"&nbsp;object's&nbsp;parent&nbsp;"HPE&nbsp;MyFlight&nbsp;Sample&nbsp;Applicatio"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:59]]></Time>
<TimeTick>1648636259</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[HPE MyFlight Sample Applicatio]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = HPE MyFlight Sample Application<br>devname = HPE MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[30-03-2022 - 16:00:59]]></Time>
<TimeTick>1648636259</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="139" status="Warning" nType="Parent description" Source="E:\DataDrivenFramework\Driver\Driver4\Library1.qfl" SourceLine="-1" >
<Disp><![CDATA[HPE MyFlight Sample Applicatio]]></Disp>
</NodeArgs>
</Step>